apiVersion: v1
kind: Service
metadata:
  name: api-smiley-service-np
  labels:
    name: api-smiley-deploy
    app: api-smiley-app
spec:
  type: NodePort
  selector:
    app: api-smiley-app
  ports:
    - protocol: TCP
      port: 3000
      nodePort: 30072



    